import React from 'react'
import { buttonVariants } from '../../components/ui/button' // shadcn export path (generated by shadcn init)

export function Button({ children, className='', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { children: React.ReactNode }){
  // If buttonVariants exists, use it; otherwise fallback to basic styling
  const cls = typeof buttonVariants === 'function' ? buttonVariants({ size: 'default', variant: 'default' }) + ' ' + className : 'px-4 py-2 rounded-xl bg-cyan-500 text-black '+className
  return <button {...props} className={cls}>{children}</button>
}

export default Button
